---
title: "Annual Data Cleaning"
output: html_notebook
---

```{r,echo=FALSE,message=FALSE}
source("librarys.R")

```
# Data Read in
```{r, message=FALSE}

gdp_raw <- 
  read.csv(here::here("raw_data/Annual/GDP_three_approaches00-21.csv")) %>% 
  clean_names()

bb_phones_raw <- 
  read_csv(here::here("raw_data/Annual/broadband_and_phone09-21.csv")) %>% 
  clean_names()

education_enrol_raw <- 
  read_csv(here::here("raw_data/Annual/education_enrolment_age.csv")) %>% 
  clean_names()

population_raw <- 
  read_csv(here::here("raw_data/Annual/population_10-19.csv")) %>% 
  clean_names()

```
# Data Cleaning

## GDP as "Per head, constant prices, constant PPPs, OECD base year" & Growth Rate data
```{r}
#Per head, constant prices, constant PPPs, OECD base year = GDP measure
gdp_value <- gdp_raw %>% 
  filter(
    measure_2 == "Per head, constant prices, constant PPPs, OECD base year"
    ) %>%
  select(country, transaction, year, value) %>% 
  pivot_wider(names_from = "transaction", 
              values_from = "value", 
              names_prefix = "usd_") %>% 
  clean_names()
  
gdp_value %>% 
  skim()

# Reference period 2015
growth_rate <- gdp_raw %>% 
  filter(measure_2 == "Growth rate") %>% 
  select(country, transaction, year, value) %>% 
  pivot_wider(names_from = "transaction", 
              values_from = "value", 
              names_prefix = "pc") %>% 
  clean_names()
  
growth_rate %>% 
  skim()


gdp_value_grth_rt <- gdp_value %>% 
  left_join(growth_rate)

gdp_value_grth_rt %>% 
  skim()
```

## Broadband and phone data
```{r}
bb_phones_raw <- bb_phones_raw %>% 
  select(-c(location, var, time_2, reference_period_code, flag_codes, flags))

fixed_bb_data <- bb_phones_raw %>% 
  filter(variable == "Fixed broadband - All subscriptions per 100 inhabitants",
           !grepl("Q", time)) %>% 
  select(country, time, value) %>% 
  rename(fixed_bb_subs_p_100 = value)
  
mobile_bb_data <- bb_phones_raw %>% 
  filter(variable == "Mobile broadband - All subscriptions",
         !grepl("Q", time)) %>% 
  select(country, time, value) %>% 
  rename(mobile_bb_subs = value)

mobile_data_use <- bb_phones_raw %>% 
  filter(
    variable == "Mobile data usage per mobile broadband subscription, GB per month",
         !grepl("Q", time)) %>% 
  select(country, time, value) %>% 
  rename(mobile_gb_per_m = value)

mob_bb_data <- fixed_bb_data %>% 
  left_join(mobile_bb_data) %>% 
  left_join(mobile_data_use) %>% 
  mutate(time = as.integer(time))
```

## Education data

```{r}
education_enrol_raw %>% 
  distinct(age_2)

education_data <- education_enrol_raw %>% 
  filter(year >= 2010,
         education_level != "Early childhood education",
         age_2 == "Total") %>% 
  select(country_2, gender, education_level, year, value) %>% 
  pivot_wider(names_from = c(gender, education_level), values_from = value) %>% 
  clean_names()

```

## Population data
```{r}

population_age_groups <- population_raw %>% 
  select(country_2, gender, age_2, year, value) %>% 
  filter(!age_2 %in% c("2 years", "Total")) %>% 
  pivot_wider(names_from = age_2, values_from = value) %>%
  clean_names() %>% 
  mutate(
    from_0_to_4 = from_0_to_2_years + x3_years + x4_years,
    from_5_to_9 = x5_years + x6_years + x7_years + x8_years + x9_years,
    from_10_to_14 = x10_years + x11_years + x12_years + x13_years + x14_years,
    from_15_to_19 = x15_years + x16_years + x17_years + x18_years + x19_years,
    from_20_to_24 = x20_years + x21_years + x22_years + x23_years + x24_years,
    from_25_to_29 = x25_years + x26_years + x27_years + x28_years + x29_years,
    from_30_to_34 = x30_years + x31_years + x32_years + x33_years + x34_years,
    from_35_to_39 = x35_years + x36_years + x37_years + x38_years + x39_years,
    from_40_to_44 = x40_years + x41_years + x42_years + x43_years + x44_years,
    from_45_to_49 = x45_years + x46_years + x47_years + x48_years + x49_years
    # ,
    # primary_age = from_5_to_9 + x10_years + x11_years + x12_years,
    # secondary_age = x13_years + x14_years + x15_years + x16_years +
    #   x17_years + x18_years
    # 
    ) %>% 
  rename(from_65_years = x65_years_or_over) %>% 
  select(-c(starts_with("x"), from_0_to_2_years)) %>% 
  relocate(4:7, .after = from_45_to_49) %>% 
  pivot_longer(cols = starts_with("from"), # c(primary_age, secondary_age), 
               names_to = "age_group", 
               values_to = "value") %>% 
  pivot_wider(names_from = c(gender, age_group), values_from = value) %>%
  clean_names()


population_gender <- population_raw %>% 
  select(country_2, gender, age_2, year, value) %>% 
  filter(age_2 == "Total") %>% 
  select(-age_2) %>% 
  pivot_wider(names_from = gender, values_from = value) %>% 
  clean_names() %>% 
  rename(population_total = total,
         population_female = female,
         population_male = male)



```

## Joining datasets
```{r}

gdp_annual_data <-  gdp_value_grth_rt %>% 
  left_join(mob_bb_data, by = c("country" = "country", 
                                "year" = "time")) %>% 
  left_join(education_data, by = c("country" = "country_2", 
                                   "year" = "year")) %>% 
  left_join(population_gender, by = c("country" = "country_2", 
                                      "year" = "year")) %>% 
  left_join(population_age_groups, by = c("country" = "country_2", 
                                      "year" = "year"))
all_annu_data <- gdp_annual_data %>% 
  select(-c(pc_changes_in_inventories, 
            pc_final_consumption_expenditure_of_non_profit_institutions_serving_households)) %>% 
  rename_with(~ sub("_isic_rev_4", "", .x), everything()) %>% 
  rename_with(~ sub("_isic_rev4", "", .x), everything()) %>% 
  rename_with(~ sub("_sna08", "", .x), everything()) %>% 
  mutate(is_uk = if_else(country == "United Kingdom", "UK", "Other OECD")) %>% 
  clean_names()
```

# Data Wrangling
### proportion function
```{r}
prop <- function(x, y, dp=2){
  round((x / y) * 100, dp)
}
```
## proportion education
```{r, message=FALSE}
all_annu_data_w_edu_props <- all_annu_data %>% 
  select(-c(starts_with("usd"), starts_with("pc"), starts_with("mobile"),
            starts_with("female_from"), starts_with("male_from"), 
            starts_with("total_from"), fixed_bb_subs_p_100)) %>% 
  drop_na() %>% 
  mutate(prop_f_at_ps = prop(female_primary_education, population_total),
         prop_m_at_ps = prop(male_primary_education, population_total),
         prop_f_at_ss = prop(female_secondary_education, population_total),
         prop_m_at_ss = prop(male_secondary_education, population_total),
         prop_f_ter_edu = prop(female_tertiary_education, population_total),
         prop_m_ter_edu = prop(male_tertiary_education, population_total)) %>% 
  select(-c(starts_with("male"), starts_with("female"), starts_with("total"), 
            population_female, population_male, is_uk))

uk_only <- all_annu_data %>% 
  filter(is_uk == "UK")


all_useable <- all_annu_data %>% 
  left_join(all_annu_data_w_edu_props) %>% 
  filter(!country == "Colombia") %>% 
  select(country, year, is_uk, starts_with("usd"), starts_with("pc")) %>% 
  drop_na() 


```

## Checking correlations
```{r, message=FALSE}

uk_mean_pc_export_of_goods <- all_useable %>% 
  group_by(country) %>% 
  summarise(mean_pc_export_of_goods_services = 
              mean(pc_exports_of_goods_and_services)) %>% 
  filter(country == "United Kingdom") %>% 
  select(mean_pc_export_of_goods_services) %>% 
  pull()

ctry_higherthan_uk <-  all_useable %>%
group_by(country) %>% 
  summarise(mean_pc_export_of_goods_services = 
              mean(pc_exports_of_goods_and_services)) %>% 
  filter(mean_pc_export_of_goods_services >= uk_mean_pc_export_of_goods) %>% 
  select(country) %>% 
  pull() %>% 
  as.list()


all_useable %>%
  filter(country %in% ctry_higherthan_uk) %>% 
  select(3:6, 31:33, 36) %>% 
   ggpairs()


```


```{r}


all_useable %>%
group_by(country, is_uk) %>% 
  summarise(mean_pc_export_of_goods_services = 
              mean(pc_exports_of_goods_and_services)) %>% 
  filter(mean_pc_export_of_goods_services >= uk_mean_pc_export_of_goods) %>% 
  ggplot(aes(fct_reorder(country, mean_pc_export_of_goods_services), 
             mean_pc_export_of_goods_services)) +
  geom_col(aes(fill = is_uk), show.legend = FALSE) +
  coord_flip() + 
  scale_fill_manual(values = c("#3AA859", "#2095C0")) +
  labs(x = "", y = "Mean Percentage of Export of Goods and Services", title = 
         "Countries with a Higher proportion Export of Goods and Services")

all_useable %>% 
  filter(country %in% ctry_higherthan_uk) %>% 
  ggplot(aes(year, pc_exports_of_goods_and_services)) +
  geom_line(aes(group = country), alpha = 0.2) +
  geom_line(data = all_useable %>% filter(country == "United Kingdom"), 
            size = 2, colour = "red") +
  xlim(2000, 2020)
  
```

```{r}

all_useable %>% 
  ggplot(aes(year, pc_final_consumption_expenditure_of_households)) +
  geom_line(aes(group = country), alpha = 0.2) +
  geom_line(data = all_useable %>% filter(country == "United Kingdom"), 
            size = 2, colour = "red") +
  xlim(2000, 2020)
```


```{r, message=FALSE}
all_annu_data %>% 
  skim()
```


# Plots

## 
```{r}
uk_mean_annual_gdp <- all_annu_data %>% 
  group_by(country, is_uk) %>% 
  summarise(mean_gdp = mean(usd_gross_domestic_product_expenditure_approach), 
            .groups = "drop") %>% 
  filter(is_uk == "UK") %>% 
  select(mean_gdp) %>% 
  pull()

all_annu_data %>% 
  group_by(country, is_uk) %>% 
  summarise(mean_gdp = mean(usd_gross_domestic_product_expenditure_approach), 
            .groups = "drop") %>% 
  filter(mean_gdp >= uk_mean_annual_gdp) %>% 
  ggplot(aes(fct_reorder(country, mean_gdp), mean_gdp)) +
  geom_col(aes(fill = is_uk)) + 
  coord_flip() +
  scale_fill_manual(values = c("#3AA859", "#2095C0"))

```

```{r}

all_annu_data %>% 
  ggplot(aes(year, usd_gross_domestic_product_expenditure_approach)) +
  geom_line(aes(group = country), alpha = 0.3) +
  geom_line(data = uk_only, aes(colour = country), size = 1.5, colour = "blue")

```

```{r}
uk_only <- all_annu_data %>% 
  filter(is_uk == "UK")

all_annu_data %>% 
  ggplot(aes(year, pc_gross_domestic_product_output_approach)) +
  geom_line(aes(group = country), alpha = 0.3) +
  geom_line(data = uk_only, aes(colour = country), colour = "blue")
```

```{r}

all_annu_data %>% 
  group_by(country, is_uk) %>% 
  summarise(mean_final_consumption_expenditure_of_households = 
              mean(usd_final_consumption_expenditure_of_households)) %>% 
  drop_na() %>% 
  ggplot(aes(fct_reorder(country, 
                         mean_final_consumption_expenditure_of_households),
             mean_final_consumption_expenditure_of_households)) +
  geom_col(aes(fill = is_uk), show.legend = FALSE) +
  coord_flip() +
  scale_fill_manual(values = c("#3AA859", "#2095C0")) +
  labs(y = "Mean Final Consumption Expenditure of Households", x = "", 
       title = "Mean Final Consumption Expenditure of Households from 2010 to 2017")

all_annu_data %>% 
  ggplot(aes(year, usd_final_consumption_expenditure_of_households)) +
  geom_line(aes(group = country), alpha = 0.3) +
  geom_line(data = uk_only, aes(colour = country), colour = "blue")

```

```{r}

all_annu_data %>% 
  group_by(country, is_uk) %>% 
  summarise(mean_usd_of_which_actual_individual_consumption = 
              mean(usd_of_which_actual_individual_consumption)) %>% 
  drop_na() %>% 
  ggplot(aes(fct_reorder(country, 
                         mean_usd_of_which_actual_individual_consumption),
             mean_usd_of_which_actual_individual_consumption)) +
  geom_col(aes(fill = is_uk)) +
  coord_flip()

all_annu_data %>% 
  ggplot(aes(year, usd_of_which_actual_individual_consumption)) +
  geom_line(aes(group = country), alpha = 0.3) +
  geom_line(data = uk_only, aes(colour = country), colour = "blue")

```



```{r}

all_annu_data %>% 
  filter(!is.na(female_primary_education)) %>%
  select(-c(starts_with("usd"), starts_with("pc"), starts_with("mobile"))) %>%
  ggplot(aes(year, population_total/1000)) + 
  geom_line(aes(group = country, colour = is_uk), show.legend = FALSE) 
 

```

