---
title: "Final project documentation template - PDA"
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
    css: ../../../styles.css
    pdf_document: default
  word_document:
    toc: yes
---

## Context

#### Business intelligence and data-driven decision making

- How can we improve productivity within Scotland and the UK overall?
  - How does the UK compare to other developed economies in terms of GDP and exports?
  - What factors might be important in predicting a country’s GDP?
  - Can you predict GDP estimates/growth for the upcoming year(s) from any of these factors?


#### Domain knowledge and the business context

The aim for Deloitte is to identify key areas which affect GDP and productivity within the UK and especially those which lag behind other developed nations, with the aim being to potentially target and improve these aspects in order to "keep up" with those nations.

This is important to Deloitte as a financial services company as any improvements in Productivity or GDP will have direct feedback into an improved market in Financial services.

Using this analysis I aim to investigate and identify some key areas and show their correlations with GDP and Productivity.

## Data

#### Internal and external data sources

Briefly describe your data sources and which were internal (provided by the organisation) and external (not sourced from the organisation's data)

In this analysis I have used a number of datasets:  
  
GDP_three_approaches00-21.csv  
broadband_and_phone09-21.csv  
population_10-19.csv  
education_enrolment_age.csv  
gdp_quarterly_10-17.csv  
pop_employ_10-17.csv  
employment_by_industry_10-17.csv  
imp_exports_value.csv  

These documents were obtained externally from the OECD statistics databases at:

https://stats.oecd.org/#

#### Types of data

What kind of data did you work with? E.g. categorical and numerical data and their sub-types.

The documents are arranged in Categorical, Numerical and Time Series.

#### Data formats

What format did your data come in? E.g. all downloaded flat files (CSV) or any data from APIs, scraping etc.

The files were all downloaded in .CSV file format.

#### Data quality and bias

Briefly describe the quality of the data and whether you have any reasons to suggest the data is biased e.g. only data from a specific demographic even though a broader demographic would be of interest to the organisation.

As the data is all broad demographical data, with very little 

## Ethics

#### Ethical issues in data sourcing and extraction

Do you have any ethical concerns regarding the sourcing and extraction of your data? 

#### Ethical implications of business requirements

Are there any ethical implications of the business requirements?

## Analysis

#### Stages in the data analysis process

What were the main stages in your data analysis process?

The steps towards my analysis were as follows:  

Read in data.
- Clean Datasets 
  - Remove erroneous variables
  - Pivot datasets accordingly
  - Filter out of scope entries
  - Rename fields
  
- Join Datasets together

- Data Wrangling
  - Wrangle data to be more consistent (ie, Population in industry figures, to proportions of population)
  - Group fields together (ie, Age to Age groups etc.)
  
- Visualisation of Data
  - Extract key points in data via plots
  
- Machine Learning 
  - Test / Train split
  - Establish a workable model on train
  - Validate model on Test
  - K-Fold Validation


#### Tools for data analysis

What were the main tools you used for your analysis?

#### Descriptive, diagnostic, predictive and prescriptive analysis

Please report under which of the below categories your analysis falls **and why** (can be more than one) 

My Analysis falls under Descriptive, Predictive and Prescriptive Analysis.

Descriptive was in the attempting to ascertain what key factors were influencing GDP in the past.

Predictive in attempting to predict future GDP in the UK.

and Prescriptive in suggesting ways in which GDP growth could be potentially improved.

::: {.emphasis}
**Descriptive Analytics** tells you what happened in the past.

**Diagnostic Analytics** helps you understand why something happened in the past.

**Predictive Analytics** predicts what is most likely to happen in the future.

**Prescriptive Analytics** recommends actions you can take to affect those outcomes.
:::


